services:
  trojan-go:
    image: p4gefau1t/trojan-go:latest
    container_name: trojan-go
    restart: unless-stopped
    ports:
      - 443:443
      - 443:443/udp
    volumes:
      - ./server.json:/etc/trojan-go/server.json
      - <your fullchain.crt>:/etc/trojan-go/fullchain.cer
      - <your private.key>:/etc/trojan-go/private.key
    command: /usr/bin/trojan-go -config /etc/trojan-go/server.json
    depends_on:
      - caddy

  trojan-go-caddy:
    image: caddy:latest
    container_name: trojan-go-caddy
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/index.html:/etc/caddy/wwwroot/index.html
      - <your fullchain.crt>:/etc/ssl/fullchain.cer
      - <your private.key>:/etc/ssl/private.key
