version: "3.9"
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # docker login to store your credentials in $HOME/.docker/config.json and then mount this config file to make it available to the Watchtower container
      # - /root/.docker/config.json:/config.json
    environment:
      WATCHTOWER_NOTIFICATION_URL: telegram://<your teletram bot token>@telegram/?channels=<your telegram chat id>
      WATCHTOWER_NOTIFICATIONS_LEVEL: warn
    command: --interval 3600 --cleanup

# Filter by disable label
# Do not update containers that have com.centurylinklabs.watchtower.enable label set to false and no --label-enable argument is passed.
# Note that only one or the other (targeting by enable label) can be used at the same time to target containers.
