version: "3.9"
services:
  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: always
    ports:
      - 8188:8188
      - 8188:8188/udp
    volumes:
      - ./config.json:/etc/xray/config.json
      - ./<your fullchain.crt>:/etc/xray/fullchain.crt
      - ./<your private.key>:/etc/xray/private.key
    depends_on:
      - caddy

  caddy:
    image: caddy:latest
    container_name: xray-caddy
    restart: always
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/index.html:/etc/caddy/wwwroot/index.html