services:
  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: always
    ports:
      - 443:443
      - 443:443/udp
    volumes:
      - ./config.json:/etc/xray/config.json
