x-common-env: &cenv
  MEILI_URL: http://wanderer-search:7700
  MEILI_MASTER_KEY: <your MEILI_MASTER_KEY>

services:
  wanderer-search:
    container_name: wanderer-search
    image: flomp/wanderer-search:latest
    environment:
      <<: *cenv
      MEILI_NO_ANALYTICS: true
    # ports:
      # - 7700:7700
    volumes:
      - ./data/data.ms:/meili_data/data.ms
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:7700/health || exit 1
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
  wanderer-db:
    container_name: wanderer-db
    image: flomp/wanderer-db:latest
    depends_on:
      wanderer-search:
        condition: service_healthy
    environment:
      <<: *cenv
    # ports:
    #   - "8090:8090"
    restart: unless-stopped
    volumes:
      - ./data/pb_data:/pb_data
  wanderer-web:
    container_name: wanderer-web
    image: flomp/wanderer-web:latest
    depends_on:
      wanderer-search:
        condition: service_healthy
      wanderer-db:
        condition: service_started
    environment:
      <<: *cenv
      ORIGIN: https://<your domain>
      BODY_SIZE_LIMIT: Infinity
      PUBLIC_POCKETBASE_URL: http://wanderer-db:8090
      PUBLIC_DISABLE_SIGNUP: true
      UPLOAD_FOLDER: /app/uploads
      UPLOAD_USER:
      UPLOAD_PASSWORD:
      PUBLIC_VALHALLA_URL: https://valhalla1.openstreetmap.de
    volumes:
      - ./data/uploads:/app/uploads
    # ports:
    #   - "3000:3000"
    restart: unless-stopped

networks:
  default:
    name: nginx-proxy-manager-app-network-ipv4
    external: true