services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      # These ports are in format <host-port>:<container-port>
      # - '80:80' # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin web portal
        # Add any other Stream port you want to expose
        # - '21:21' # FTP

        # Uncomment the next line if you uncomment anything in the section
        # environment:
        # Uncomment this if you want to change the location of
        # the SQLite DB file within the container
        # DB_SQLITE_FILE: "/data/database.sqlite"

        # Uncomment this if IPv6 is not enabled on your host
        # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - <your fullchain cer>:/data/custom_ssl/npm-2/fullchain.pem
      - <your private key>:/data/custom_ssl/npm-2/privkey.pem
      - ./letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
networks:
  default:
    external:
      # docker network create --ipv6 --driver bridge --subnet 172.13.0.0/16 --subnet 2001:db9:1::/64 nginx-proxy-manager-app-network
      name: nginx-proxy-manager-app-network
